### PR TITLE
SA api consumption giphy response with 1 gif or more

### PR DESCRIPTION
**Pull request by Sergio-Azcona**
1. completed the downgrading rails & ruby version process; now running:
- ruby "2.7.4"
- gem 'rails', '~> 5.2.8', '>= 5.2.8.1'

2. created fixture directories (dir) (new dir in bold, (#s relate to files within these dir as noted below)): fixture>services>giphy>happy_path (1A.) & sad_path (2A.)

      1A.A. created happy_path>full_phrase_response
      - response when full sentence is search. results for search: "If I throw a stick, will you leave?"

      1A.B. created happy_path>no_data_response
      - search produces no gif results; 200 response with empty data array
      
      2A.A. sad_path>no_api_key_response
      - no API key is sent
      
      2A.B. sad_path>unauthorized_(apiKey_issue)_response
      - API key submitted is not authorized/invalid

3.  created spec>service>giphy test for responses with data 1+ (gifs)
- test 1: expect high level keys to be present
- test 2: expect secondary keys (data, pagination, meta) to have have certain keys (those of interest to us) and data type

### CODE REVIEW

**Comment by Sergio-Azcona** [comment]
Happy to review this together as a lot of changes seem to have occurred... but what what drop those changes was downgrading the `ruby` and `rails version` (I forgot to pull main after Bryan downgraded us... thus I had to do it myself as I did not want to lose data I had)

**Comment by devinpile** [comment]
let's specify (for those not around during discussion) as to 'why?' ... you say 'what' i.e. ('changed ruby/rails version') but a more explicit direction would include WHY changing the version was necessary

**Comment by devinpile** [comment]
for developer empathy, make sure your PR  can be interpreted by someone whom does not have background knowledge(in laymen's terms); ie. "Consuming ____ API", "Created file tree for tests", "Included 'sad_path' testing", etc.
Then, when necessary, give detailed description. But we(the team) can see your changes and can interpret a lot of the detail from the code you're writing and therefore may not be pertinent. 
IDK... thoughts from the group??

**Comment by devinpile** [comment]
i know Bryan left this comment, but since it is not showing up, i will reiterate: 
(also, why can't i see the comments that i know he made??)

Clean up shop - **remove your 'prys'** 
remove any unnecessary comments out of the file - ie. the commented out require files at the top of the page; you can make a new commit that explains deleting those because we changed versions and do not need to require those files anymore

**Comment by Sergio-Azcona** [comment]
Issues noted in this repo were addressed in PR #6 . Closing this PR as the goal accomplished is the same with changes noted.

**Pull request closed without merging**
